Feature item error
CSID-DGU/2021-1-OSSPC-BINSU-7 pull request #67
Opened 2021-05-31 12:03 UTC by Awarduuu

- 아이템 모서리에서 사용 안되는 에러 해결
- pvp모드 관련 코드 삭제

2021-05-31 12:08 UTC, bin9841 approved these changes

2021-05-31 12:33 UTC, shxnyoung requested changes
def draw_1Pboard, draw_2Pboard도 pvp 관련 코드로 삭제해야됩니다

2021-05-31 12:34 UTC, shxnyoung requested changes
def set_initial_values에도 global 및 변수에서 pvp 삭제해야됩니다

2021-06-03 03:46 UTC, Awarduuu commented
global 변수 삭제 및 pvp 관련 함수 모두 삭제 완료했습니다

2021-06-03 03:58 UTC, merged